language: java
jdk:
   - oraclejdk8

git:
  submodules: false

services:
  - mongodb
  - rabbitmq

addons:
  hosts:
    - MONGODB_HOST
    - RABBITMQ_HOST

install: true
script: ./gradlew clean build integTest -Dspring.profiles.active=travisci
